### ISSUE TITLE
Add Initial Web Project For SimpleQuoridor

### ISSUE THREAD

**Issue by leesangpil** [Jung-hyelim/SimpleQuoridor#1]
@Jung-hyelim 님,
스프링 웹 프로젝트를 생성합니다.

왠만하면 최신버전으로 하시면 될 것 같습니다.
- 자바, 스프링, 톰캣.. 등

기타(추후) 작업은 계속 이 "이슈" 탭에서 관리하도록 하겠습니다.
궁금한점은 메신저 or 코멘트 부탁해요 ^^

**Comment by leesangpil** [comment]
@Jung-hyelim 우리 그리구 만나서 사진 바꿔용 히힣ㅋㅋㅋ
아 그리구.. 이슈 및 여러가지 세팅해놔서 메일 폭탄이 갔을것 같은데.. 당황하지 마라용 ㅎㅎ
설명이 부족한 부분이 있으면 언제든지 코멘트 줘도 되구, 물어봐도 되니까 ㅎㅎ

**Comment by leesangpil** [comment]
@Jung-hyelim 이모티콘은 메일이 오지 않는다는점 알아두세용 ^^

**Comment by Jung-hyelim** [comment]
@leesangpil 알겠습니다!

**Comment by leesangpil** [comment]
@Jung-hyelim 님, 프로젝트 생성 후 스펙은 "위키" 탭에 정리해 주세요
