### ISSUE TITLE
Install Lombok Plugin

### ISSUE THREAD

**Issue by leesangpil** [Jung-hyelim/SimpleQuoridor#6]
롬복 플러그인을 적용합니다.(로컬 환경(IDE)에 따라 설정이 다를 수 있습니다.)
1. 프로젝트 maven dependancy 설정
2. 개인 로컬환경에 따라 lombok plugin 설치

이는 코드에 가독성과 생산성 향상에 큰 도움이 될 수 있습니다.

**Comment by Jung-hyelim** [comment]
wiki에 정리했습니다. @leesangpil

**Comment by leesangpil** [comment]
@Jung-hyelim 확인했습니다. IntelliJ 롬복 적용사례 추가하고 이슈 닫겠습니다.
