### ISSUE TITLE
Apply Swagger 2

### ISSUE THREAD

**Issue by leesangpil** [Jung-hyelim/SimpleQuoridor#7]
API를 문서로 일일이 정의하기 보다는 Swagger라는 툴을 이용해 세팅하는것이 좋을것 같습니다.
(REST API 관련하여 같이 고민할 부분이 생길 것입니다. + (패키지 및 코드 아키텍처 까지..)
@Jung-hyelim 님,
현재 Swagger2 버전이 나온것으로 알고 있는데, 설정 부탁드립니다 ^^
언제든지 궁금한점 연락주시면 되용~

실제로 본 프로젝트에서는 API서버를 따로 두고 돌리는 것은 아니지만, 향후 사용법을 알아둔다면 유용할 수 있습니다.

**Comment by leesangpil** [comment]
@Jung-hyelim PR 머지되면 이슈 닫아 주세요.

**Comment by leesangpil** [comment]
@Jung-hyelim wiki에도 간략하게 정리해 주세요.

**Comment by Jung-hyelim** [comment]
@leesangpil  PR 머지했습니다. wiki에는 추후에 정리하겠습니다.
